<?php

namespace hws_base_tools;

use Hexa\PluginCore\ContentCleanup\ArticleMediaCleanupAjaxController;
use Hexa\PluginCore\ContentCleanup\ArticleMediaCleanupConfig;
use Hexa\PluginCore\ContentCleanup\ArticleMediaCleanupRenderer;
use Hexa\PluginCore\ContentCleanup\BackupCleanupAjaxController;
use Hexa\PluginCore\ContentCleanup\BackupCleanupConfig;
use Hexa\PluginCore\ContentCleanup\BackupCleanupRenderer;
use Hexa\PluginCore\ContentCleanup\ContentCleanupAjaxController;
use Hexa\PluginCore\ContentCleanup\ContentCleanupConfig;
use Hexa\PluginCore\ContentCleanup\ContentCleanupRenderer;

defined( 'ABSPATH' ) || exit;

const HWS_CONTENT_CLEANUP_NONCE_ACTION = 'hws_base_tools_content_cleanup';

function hws_content_cleanup_config(): ContentCleanupConfig {
    return new ContentCleanupConfig(
        [
            'root_id'                => 'hws-content-cleanup',
            'title'                  => 'Cleanup',
            'description'            => 'Reports pages that look like duplicate, stale, or cleanup candidates. The report is generated by Hexa WP Core rules with no manual filters.',
            'capability'             => 'manage_options',
            'nonce_action'           => HWS_CONTENT_CLEANUP_NONCE_ACTION,
            'nonce_field'            => 'nonce',
            'scan_action'            => 'hws_content_cleanup_scan',
            'trash_action'           => 'hws_content_cleanup_trash',
            'delete_action'          => 'hws_content_cleanup_delete',
            'post_types'             => [ 'page' => 'Pages' ],
            'statuses'               => [
                'publish' => 'Published',
                'draft'   => 'Draft',
                'private' => 'Private',
                'pending' => 'Pending',
                'any'     => 'Any active status',
            ],
            'default_post_type'      => 'page',
            'default_status'         => 'any',
            'default_published_days' => 0,
            'default_modified_days'  => 0,
            'default_limit'          => 500,
            'max_limit'              => 1000,
            'show_filters'           => false,
            'count_label'            => 'Reported',
            'detection_rules'        => [
                [
                    'id'                 => 'home_not_front',
                    'label'              => 'Home',
                    'tone'               => 'warning',
                    'terms'              => [ 'home' ],
                    'fields'             => [ 'title', 'slug' ],
                    'match'              => 'word',
                    'exclude_option_ids' => [ 'page_on_front' ],
                    'description'        => 'Contains home in the title or slug but is not the assigned WordPress front page.',
                ],
                [
                    'id'          => 'old_delete',
                    'label'       => 'Old/Delete',
                    'tone'        => 'danger',
                    'terms'       => [ 'old', 'delete' ],
                    'fields'      => [ 'title', 'slug' ],
                    'match'       => 'word',
                    'description' => 'Contains old or delete in the title or slug.',
                ],
            ],
            'protected_post_ids'     => __NAMESPACE__ . '\\hws_content_cleanup_protected_page_ids',
            'empty_message'          => 'No cleanup candidates matched the Core report rules.',
        ]
    );
}

function hws_content_cleanup_protected_page_ids(): array {
    $ids = [];

    foreach ( [ 'page_on_front', 'page_for_posts', 'wp_page_for_privacy_policy' ] as $option ) {
        $value = function_exists( 'get_option' ) ? absint( get_option( $option ) ) : 0;
        if ( $value > 0 ) {
            $ids[] = $value;
        }
    }

    return array_values( array_unique( $ids ) );
}

function hws_backup_file_cleanup_config(): BackupCleanupConfig {
    return new BackupCleanupConfig(
        [
            'root_id'       => 'hws-backup-file-cleanup',
            'title'         => 'Backup Files',
            'description'   => 'Reports backup files from configured WordPress backup plugin folders. Delete actions run through Hexa WP Core with a loader and activity log for each file.',
            'capability'    => 'manage_options',
            'nonce_action'  => HWS_CONTENT_CLEANUP_NONCE_ACTION,
            'nonce_field'   => 'nonce',
            'scan_action'   => 'hws_backup_file_cleanup_scan',
            'delete_action' => 'hws_backup_file_cleanup_delete',
            'locations'     => hws_content_cleanup_backup_locations(),
            'empty_message' => 'No backup files were detected in the configured backup locations.',
        ]
    );
}

function hws_content_cleanup_backup_locations(): array {
    return [
        'all-in-one-wp-migration' => [
            'name'       => 'All-in-One WP Migration',
            'path'       => WP_CONTENT_DIR . '/ai1wm-backups/',
            'extensions' => [ 'wpress' ],
        ],
        'updraftplus' => [
            'name'       => 'UpdraftPlus',
            'path'       => WP_CONTENT_DIR . '/updraft/',
            'extensions' => [ 'zip', 'gz', 'sql' ],
        ],
        'backwpup' => [
            'name'       => 'BackWPup',
            'path'       => WP_CONTENT_DIR . '/uploads/backwpup*/',
            'extensions' => [ 'zip', 'tar', 'gz' ],
        ],
        'duplicator' => [
            'name'       => 'Duplicator',
            'path'       => WP_CONTENT_DIR . '/backups-dup-lite/',
            'extensions' => [ 'zip', 'daf' ],
        ],
        'duplicator-pro' => [
            'name'       => 'Duplicator Pro',
            'path'       => WP_CONTENT_DIR . '/backups-dup-pro/',
            'extensions' => [ 'zip', 'daf' ],
        ],
        'wpvivid' => [
            'name'       => 'WPVivid',
            'path'       => WP_CONTENT_DIR . '/wpvivid/',
            'extensions' => [ 'zip' ],
        ],
        'backup-migration' => [
            'name'       => 'Backup Migration',
            'path'       => WP_CONTENT_DIR . '/backup-migration*/',
            'extensions' => [ 'zip' ],
        ],
    ];
}

function hws_article_media_cleanup_config(): ArticleMediaCleanupConfig {
    return new ArticleMediaCleanupConfig(
        [
            'root_id'             => 'hws-article-media-cleanup',
            'title'               => 'Article & Media Cleanup',
            'description'         => 'Filter posts, preview matches, and delete all matching posts in AJAX batches. Associated media deletion is off by default and must be explicitly enabled.',
            'capability'          => 'manage_options',
            'nonce_action'        => HWS_CONTENT_CLEANUP_NONCE_ACTION,
            'nonce_field'         => 'nonce',
            'scan_action'         => 'hws_article_media_cleanup_scan',
            'delete_action'       => 'hws_article_media_cleanup_delete',
            'batch_delete_action' => 'hws_article_media_cleanup_batch_delete',
            'post_types'          => [ 'post' => 'Posts' ],
            'statuses'            => [
                'publish' => 'Published',
                'draft'   => 'Draft',
                'private' => 'Private',
                'pending' => 'Pending',
                'any'     => 'Any active status',
            ],
            'default_post_type'   => 'post',
            'default_status'      => 'publish',
            'default_keep_recent' => 25,
            'default_limit'       => 50,
            'max_limit'           => 250,
            'default_batch_size'  => 50,
            'max_batch_size'      => 100,
            'empty_message'       => 'No matching articles were found for the selected filters.',
        ]
    );
}

function hws_register_content_cleanup_ajax(): void {
    static $registered = false;

    if ( $registered ) {
        return;
    }

    ( new ContentCleanupAjaxController( hws_content_cleanup_config() ) )->register();
    ( new BackupCleanupAjaxController( hws_backup_file_cleanup_config() ) )->register();
    ( new ArticleMediaCleanupAjaxController( hws_article_media_cleanup_config() ) )->register();

    $registered = true;
}
add_action( 'init', __NAMESPACE__ . '\\hws_register_content_cleanup_ajax', 20 );

function display_settings_cleanup(): void {
    hws_register_content_cleanup_ajax();

    ( new ContentCleanupRenderer( hws_content_cleanup_config() ) )->render();
    ( new BackupCleanupRenderer( hws_backup_file_cleanup_config() ) )->render();
    ( new ArticleMediaCleanupRenderer( hws_article_media_cleanup_config() ) )->render();
}
