<?php

namespace hws_base_tools;

use Hexa\PluginCore\ContentCleanup\ContentCleanupAjaxController;
use Hexa\PluginCore\ContentCleanup\ContentCleanupConfig;
use Hexa\PluginCore\ContentCleanup\ContentCleanupRenderer;

defined( 'ABSPATH' ) || exit;

const HWS_CONTENT_CLEANUP_NONCE_ACTION = 'hws_base_tools_content_cleanup';

function hws_content_cleanup_config(): ContentCleanupConfig {
    return new ContentCleanupConfig(
        [
            'root_id'                => 'hws-content-cleanup',
            'title'                  => 'Cleanup',
            'description'            => 'Reports pages that look like duplicate, stale, or cleanup candidates. The report is generated by Hexa WP Core rules with no manual filters.',
            'capability'             => 'manage_options',
            'nonce_action'           => HWS_CONTENT_CLEANUP_NONCE_ACTION,
            'nonce_field'            => 'nonce',
            'scan_action'            => 'hws_content_cleanup_scan',
            'trash_action'           => 'hws_content_cleanup_trash',
            'delete_action'          => 'hws_content_cleanup_delete',
            'post_types'             => [ 'page' => 'Pages' ],
            'statuses'               => [
                'publish' => 'Published',
                'draft'   => 'Draft',
                'private' => 'Private',
                'pending' => 'Pending',
                'any'     => 'Any active status',
            ],
            'default_post_type'      => 'page',
            'default_status'         => 'any',
            'default_published_days' => 0,
            'default_modified_days'  => 0,
            'default_limit'          => 500,
            'max_limit'              => 1000,
            'show_filters'           => false,
            'count_label'            => 'Reported',
            'detection_rules'        => [
                [
                    'id'                 => 'home_not_front',
                    'label'              => 'Home',
                    'tone'               => 'warning',
                    'terms'              => [ 'home' ],
                    'fields'             => [ 'title', 'slug' ],
                    'match'              => 'word',
                    'exclude_option_ids' => [ 'page_on_front' ],
                    'description'        => 'Contains home in the title or slug but is not the assigned WordPress front page.',
                ],
                [
                    'id'          => 'old_delete',
                    'label'       => 'Old/Delete',
                    'tone'        => 'danger',
                    'terms'       => [ 'old', 'delete' ],
                    'fields'      => [ 'title', 'slug' ],
                    'match'       => 'word',
                    'description' => 'Contains old or delete in the title or slug.',
                ],
            ],
            'protected_post_ids'     => __NAMESPACE__ . '\\hws_content_cleanup_protected_page_ids',
            'empty_message'          => 'No cleanup candidates matched the Core report rules.',
        ]
    );
}

function hws_content_cleanup_protected_page_ids(): array {
    $ids = [];

    foreach ( [ 'page_on_front', 'page_for_posts', 'wp_page_for_privacy_policy' ] as $option ) {
        $value = function_exists( 'get_option' ) ? absint( get_option( $option ) ) : 0;
        if ( $value > 0 ) {
            $ids[] = $value;
        }
    }

    return array_values( array_unique( $ids ) );
}

function hws_register_content_cleanup_ajax(): void {
    static $registered = false;

    if ( $registered ) {
        return;
    }

    ( new ContentCleanupAjaxController( hws_content_cleanup_config() ) )->register();

    $registered = true;
}
add_action( 'init', __NAMESPACE__ . '\\hws_register_content_cleanup_ajax', 20 );

function display_settings_cleanup(): void {
    hws_register_content_cleanup_ajax();

    ( new ContentCleanupRenderer( hws_content_cleanup_config() ) )->render();
}
