<?php namespace hws_base_tools;

function regsiter_acf_post_podcast()
{

        if ( ! function_exists( 'acf_add_local_field_group' ) ) {
            return;
        }
    
        acf_add_local_field_group( array(
        'key' => 'group_6844c5d5cf57f',
        'title' => 'Single Post Podcast - 2025',
        'fields' => array(
            array(
                'key' => 'field_6844c5f82ace2',
                'label' => 'Episode URLs',
                'name' => 'urls',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6844c5f82ace3',
                        'label' => 'Spotify',
                        'name' => 'spotify',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://open.spotify.com/show/0fHCjIg7f7iJ4ytgMqYSJC" target=_blank>https://open.spotify.com/show/0fHCjIg7f7iJ4ytgMqYSJC</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace4',
                        'label' => 'Pandora',
                        'name' => 'pandora',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace5',
                        'label' => 'SoundCloud',
                        'name' => 'soundcloud',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://soundcloud.com/mikeyperes" target=_blank>https://soundcloud.com/mikeyperes</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace6',
                        'label' => 'Google Podcast',
                        'name' => 'google',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://podcasts.google.com/feed/aHR0cHM6Ly9wb2RjYXN0Lm1pY2hhZWxwZXJlcy5jb20vZmVlZC9wb2RjYXN0Lw" target=_blank>https://podcasts.google.com/feed/aHR0cHM6Ly9wb2RjYXN0Lm1pY2hhZWxwZXJlcy5jb20vZmVlZC9wb2RjYXN0Lw</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace7',
                        'label' => 'Deezer',
                        'name' => 'deezer',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.deezer.com/show/3651277" target=_blank>https://www.deezer.com/show/3651277</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace8',
                        'label' => 'Amazon',
                        'name' => 'amazon',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://music.amazon.com/podcasts/d4dba625-8ea3-420e-bb89-d358e6e17605/the-michael-peres-podcast-w-mikey-peres" target=_blank>https://music.amazon.com/podcasts/d4dba625-8ea3-420e-bb89-d358e6e17605/the-michael-peres-podcast-w-mikey-peres</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82ace9',
                        'label' => 'Apple Podcast',
                        'name' => 'apple',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://podcasts.apple.com/us/podcast/the-michael-peres-podcast-w-mikey-peres/id1318140329" target=_blank>https://podcasts.apple.com/us/podcast/the-michael-peres-podcast-w-mikey-peres/id1318140329</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acea',
                        'label' => 'iHeart',
                        'name' => 'iheart',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.iheart.com/podcast/269-the-michael-peres-podcast-65366400/" target=_blank>https://www.iheart.com/podcast/269-the-michael-peres-podcast-65366400/</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82aceb',
                        'label' => 'Audible',
                        'name' => 'audible',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.audible.com/pd/The-Michael-Peres-Podcast-w-Mikey-Peres-Podcast/B09Z8S39QS" target=_blank>https://www.audible.com/pd/The-Michael-Peres-Podcast-w-Mikey-Peres-Podcast/B09Z8S39QS</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acec',
                        'label' => 'Stitcher',
                        'name' => 'stitcher',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.stitcher.com/show/the-michael-peres-podcast" target=_blank>https://www.stitcher.com/show/the-michael-peres-podcast</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82aced',
                        'label' => 'Blubrry',
                        'name' => 'blubrry',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://blubrry.com/mikeyperes/" target=_blank>https://blubrry.com/mikeyperes/</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acee',
                        'label' => 'Gaana',
                        'name' => 'gaana',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acef',
                        'label' => 'Podchaser',
                        'name' => 'podchaser',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.podchaser.com/podcasts/the-michael-peres-podcast-2258457" target=_blank>https://www.podchaser.com/podcasts/the-michael-peres-podcast-2258457</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf0',
                        'label' => 'JioSaavn',
                        'name' => 'jiosaavn',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf1',
                        'label' => 'TuneIn',
                        'name' => 'tunein',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://tunein.com/podcasts/Technology-Podcasts/The-Michael-Peres-Podcast-p1333869/" target=_blank>https://tunein.com/podcasts/Technology-Podcasts/The-Michael-Peres-Podcast-p1333869/</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf2',
                        'label' => 'iMDB',
                        'name' => 'imdb',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://www.imdb.com/title/tt16410896/" target=_blank>https://www.imdb.com/title/tt16410896/</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf3',
                        'label' => 'Anghami',
                        'name' => 'anghami',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf4',
                        'label' => 'YouTube',
                        'name' => 'youtube',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '<a href="https://youtube.com/@mikeyperes" target=_blank>https://youtube.com/@mikeyperes</a>',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf5',
                        'label' => 'Instagram',
                        'name' => 'instagram',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c5f82acf6',
                        'label' => 'ListenNotes',
                        'name' => 'listennotes',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6844c8f60702c',
                        'label' => 'RSS',
                        'name' => 'rss',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_6844c7776e21e',
                'label' => 'Host(s)',
                'name' => 'hosts',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'profile',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 1,
                'allow_null' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_6844c7e536052',
                'label' => 'Summary',
                'name' => 'summary',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6844c7e536056',
                'label' => 'Audio URL',
                'name' => 'audio_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6844c7e536050',
                'label' => 'Audio File',
                'name' => 'audio',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => '',
                'library' => '',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_6844c7e536051',
                'label' => 'Episode Number',
                'name' => 'number',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6844c7e536053',
                'label' => 'Active',
                'name' => 'active',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6844c7e536054',
                'label' => 'Season',
                'name' => 'season',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6844c7e536055',
                'label' => 'Duration',
                'name' => 'duration',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6844c7e536058',
                'label' => 'Same As (Schema Dump)',
                'name' => 'same_as',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6844c7e536057',
                'label' => 'Citations',
                'name' => 'citations',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
              
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    
    
}

?>