<?php namespace hws_base_tools;
function enable_smp_cpt_teammember(){

	register_post_type( 'team-member', array(
	'labels' => array(
		'name' => 'Team Members',
		'singular_name' => 'Team Member',
		'menu_name' => 'Team Members',
		'all_items' => 'All Team Members',
		'edit_item' => 'Edit Team Member',
		'view_item' => 'View Team Member',
		'view_items' => 'View Team Members',
		'add_new_item' => 'Add New Team Member',
		'add_new' => 'Add New Team Member',
		'new_item' => 'New Team Member',
		'parent_item_colon' => 'Parent Team Member:',
		'search_items' => 'Search Team Members',
		'not_found' => 'No team members found',
		'not_found_in_trash' => 'No team members found in Trash',
		'archives' => 'Team Member Archives',
		'attributes' => 'Team Member Attributes',
		'insert_into_item' => 'Insert into team member',
		'uploaded_to_this_item' => 'Uploaded to this team member',
		'filter_items_list' => 'Filter team members list',
		'filter_by_date' => 'Filter team members by date',
		'items_list_navigation' => 'Team Members list navigation',
		'items_list' => 'Team Members list',
		'item_published' => 'Team Member published.',
		'item_published_privately' => 'Team Member published privately.',
		'item_reverted_to_draft' => 'Team Member reverted to draft.',
		'item_scheduled' => 'Team Member scheduled.',
		'item_updated' => 'Team Member updated.',
		'item_link' => 'Team Member Link',
		'item_link_description' => 'A link to a team member.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'trackbacks',
		3 => 'editor',
		4 => 'excerpt',
		5 => 'revisions',
		6 => 'page-attributes',
		7 => 'thumbnail',
		8 => 'custom-fields',
		9 => 'post-formats',
	),
	'taxonomies' => array(
		0 => 'category',
	),
	'delete_with_user' => false,
) );}
?>