<?php namespace hws_base_tools;
function enable_smp_cpt_organization(){

	register_post_type( 'organization', array(
	'labels' => array(
		'name' => 'Organizations',
		'singular_name' => 'Organization',
		'menu_name' => 'Organization',
		'all_items' => 'All organization',
		'edit_item' => 'Edit organization',
		'view_item' => 'View organization',
		'view_items' => 'View organization',
		'add_new_item' => 'Add New organization',
		'add_new' => 'Add New organization',
		'new_item' => 'New organization',
		'parent_item_colon' => 'Parent organization:',
		'search_items' => 'Search organization',
		'not_found' => 'No organization found',
		'not_found_in_trash' => 'No organization found in Trash',
		'archives' => 'organization Archives',
		'attributes' => 'organization Attributes',
		'insert_into_item' => 'Insert into organization',
		'uploaded_to_this_item' => 'Uploaded to this organization',
		'filter_items_list' => 'Filter organization list',
		'filter_by_date' => 'Filter organization by date',
		'items_list_navigation' => 'organization list navigation',
		'items_list' => 'organization list',
		'item_published' => 'organization published.',
		'item_published_privately' => 'organization published privately.',
		'item_reverted_to_draft' => 'organization reverted to draft.',
		'item_scheduled' => 'organization scheduled.',
		'item_updated' => 'organization updated.',
		'item_link' => 'organization Link',
		'item_link_description' => 'A link to a organization.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'trackbacks',
		3 => 'editor',
		4 => 'excerpt',
		5 => 'revisions',
		6 => 'page-attributes',
		7 => 'thumbnail',
		8 => 'custom-fields',
		9 => 'post-formats',
	),
	'taxonomies' => array(
		0 => 'category',
	),
	'delete_with_user' => false,
) );}
?>
